import { Router } from "express"
import { refreshAccessToken, registerUser } from "../controllers/user.contollers.js"
import { upload } from "../middlewares/multer.middleware.js"
import { loginUser } from "../controllers/user.contollers.js"
import { logoutUser } from "../controllers/user.contollers.js"
import { verifyJWT } from "../middlewares/auth.middleware.js"